### ISSUE TITLE
Choose blog system / CRM system to use

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [workwork/blog-blog#1]
We need a blog system for blog-blog so we can blog about blog-blog.

Possible alternatives:
- https://hexo.io/
- Wordpress

Please provide additional alternatives.

**Comment by cybic** [comment]
We could of course bootstrap a new cms. I suggest calling it blog-blog-blog.

**Comment by stephan-nordnes-eriksen** [comment]
In all seriousness: We could run the blog as a [GitHub page](https://pages.github.com/)

**Comment by stephan-nordnes-eriksen** [comment]
I think we should choose Github Pages with Jekyll.
